name: ci
permissions:
  contents: read
on:
  push:
jobs:
  job:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: terraform validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate